# Generated by Django 5.1.6 on 2025-06-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=20),
        ),
    ]
